//URL TO MODIFY
const baseURL = "http://localhost:8000/api/v1/titles/?imdb_score=&imdb_score_min=9.3" 
const ninetiesURL = "http://localhost:8000/api/v1/titles/?min_year=1990&max_year=1999&imdb_score=&imdb_score_min=8.8"
const nicolasCageURL = "http://localhost:8000/api/v1/titles/?imdb_score=&imdb_score_min=7.3&actor=Nicolas+Cage&actor_contains="
const adventureURL = "http://localhost:8000/api/v1/titles/?genre=&genre_contains=adventure&imdb_score=&imdb_score_min=8.6"

let alreadyShownFilm = []


async function getLinksPages(url) {
    // Get the different pages of a research
    // Arg : A root URL
    // Return : An array of URLs

    let linkArray = []
    while (true) {
        if (Boolean(url) == true) {
        const Res= fetch(url);
        const response= await Res;
        const json = await response.json();
        linkArray.push(url)
        url = json["next"]
        }
        else {
            return linkArray
    }
 }
}

async function getFilmsContent(getLinksPages) {
    // Get the films json datas
    // Arg : The getLinksPages function (containing array of URLs)
    // Return : An array containing films as json datas

    const linksArray = await getLinksPages
    let ContentArray = []

    for (page in linksArray) {
        const Res= fetch(linksArray[page]);
        const response= await Res;
        const json = await response.json()
        for (film in json["results"]) {
            ContentArray.push(json["results"][film])
        }
    }
    return ContentArray
}

async function returnBestFilm(getFilmsContent) {
    // Return the best film based on two criteria, the
    // imdb score and the number of votes
    // Arg : The getfilmsContent function ( Array of films in json format)
    // Return : The best film, format : json

    let filmsArray = await getFilmsContent
    let bestFilm = filmsArray[0]

    for (film in filmsArray) {
        if (filmsArray[film]["imdb_score"] >= bestFilm["imdb_score"] ) {
            if (filmsArray[film]["votes"] > bestFilm["votes"] ) {
            bestFilm = filmsArray[film]
            }
        }
    }
    alreadyShownFilm.push(bestFilm.title)

    return bestFilm
}


async function returnBestFilms(array) {  
    // Return the best films 
    // Arg : A array of films (in json format)
    // Return : A sorted array of films (in json format)

    let numberOffilms = 7
    let arr = await array;

    sortedarr = await arr.sort(function(a,b) {
        return b.imdb_score - a.imdb_score;
    })

    let filteredArray = []
    let index = 0 
    while (true) {
        if (!alreadyShownFilm.includes(sortedarr[index].title)) {
            alreadyShownFilm.push(sortedarr[index].title)
            filteredArray.push(sortedarr[index])
            index += 1
        }
        if (filteredArray.length == numberOffilms) { 
            break
        }
        else if (alreadyShownFilm.includes(sortedarr[index].title)) {
            index += 1 
        }
    }
    return filteredArray
}


async function getDatas() {
    // Return all the chosen datas
    // Return : An array of Films datas in JSON format
    const greatFilms = await getFilmsContent(getLinksPages(baseURL))
    const bestFilm = await returnBestFilm(greatFilms)
    const bestFilms = await returnBestFilms(greatFilms)
    const bestNinetiesFilms = await returnBestFilms(getFilmsContent(getLinksPages(ninetiesURL)))
    const nicolasCageBestFilms = await returnBestFilms(getFilmsContent(getLinksPages(nicolasCageURL)))
    const bestAdventureFilms = await returnBestFilms(getFilmsContent(getLinksPages(adventureURL)))
    const films_array = [bestFilm, bestFilms, bestNinetiesFilms, nicolasCageBestFilms, bestAdventureFilms]

    return films_array
}


async function showImage(getFunctionResult) {
    // Modify films covers
    // Arg : An array of JSON datas generated by getDatas()
    filmsArray = await getFunctionResult;
    let index = 0
    for (value in filmsArray) {
        const filmByCategory = filmsArray[value]
        if (value != 0) {
            for (film in filmByCategory) {
                document.getElementById("img"+index).src = filmByCategory[film]['image_url'];
                index += 1;
                
            }
        }
    }
}


async function addFilmsInfos(getFunctionResult) { 
    // Modify the modal information 
    // Arg : An array of JSON datas generated by getDatas()

    filmsArray = await getFunctionResult;
    let index = 0
    for (value in filmsArray) {
        const filmByCategory = filmsArray[value]
        if (value == 0) {
            let content = document.getElementById('modal'+index+"0");
            content.firstElementChild.firstElementChild.innerHTML = filmsArray[value]['title'];
            generateTable(index, filmsArray[value]);

            } 
        else {
            for (film in filmByCategory) {
                let content = document.getElementById('modal'+index);
                console.log(content)
                content.firstElementChild.firstElementChild.innerHTML = filmByCategory[film]['title'];
                generateTable(index+1, filmByCategory[film]);

                index += 1;
            }
        }
    }
} 


async function generateTable(tableIndex, data) {
    // Create tables inside the html in order to represent films datas
    // Args : The table index : an int, data : film's informations ( JSON format )
    data = await data
    table = document.querySelectorAll("table")[tableIndex]
    unwantedElements = ["id","url","imdb_url","title","image_url"]
    for (let element in data) {
      if (!unwantedElements.includes(element)) {
        let tableKey = element;
        let tableValue = data[element];
        let row = table.insertRow();
  
        let cell1 = row.insertCell();
        let cell2 = row.insertCell();
  
        let text1 = document.createTextNode(tableKey);
        let text2 = document.createTextNode(tableValue);

        cell1.appendChild(text1);
        cell2.appendChild(text2);
      }
    }
  }


function iteamGeneration() {


    for (item in document.getElementsByClassName("item")) {

        if (item < document.getElementsByClassName("item").length) {

            //// Creating the input
            const input = document.createElement("input");
            input.setAttribute("data-modal-target",("#modal"+(item)))
            input.id = ("img"+(item));
            input.type = "image";
            input.src = "ressources/50Ok.gif";
            input.name = "saveForm";
            input.className = "btTxt submit";
            input.alt = "";
        
            // Creating the modal
            const modal = document.createElement("div");
            modal.className = "modal";
            modal.id = ("modal"+(item));
        
            // Adding the input and the modal to the html
            const element = document.getElementsByClassName("item")[item];
            element.appendChild(input);
            element.appendChild(modal);
        
            // Creating the modal-header
            const modalHeader = document.createElement("div");
            modalHeader.className = "modal-header";
        
            const selectedModal = document.getElementById("modal"+(item));
            selectedModal.appendChild(modalHeader);
        
            const modalTitle = document.createElement("div");
            modalTitle.className = "title";
            const button = document.createElement("button");
            button.setAttribute("data-close-button","");
            button.className = "closeButton";
            const node = document.createTextNode("X");
            button.appendChild(node);
        
            const SelectedSubModal = document.getElementsByClassName("modal-header")[parseInt(item)+1];
            SelectedSubModal.appendChild(modalTitle);
            SelectedSubModal.appendChild(button)
        
            // Creating the modal-body 
            const modalBody = document.createElement("div");
            modalBody.className = "modal-body";
        
            selectedModal.appendChild(modalBody);
        
            // Creating the table
            const modalTable = document.createElement("table");
            selectedModal.appendChild(modalTable);

        }

    }

}

function modalManager() {

    const openModalButtons = document.querySelectorAll('[data-modal-target]')
    const closeModalButtons = document.querySelectorAll('[data-close-button]')
    const overlay = document.getElementById('overlay')
    
    openModalButtons.forEach(button => {
      button.addEventListener('click', () => {
        const modal = document.querySelector(button.dataset.modalTarget) // --- 
        openModal(modal)
      })
    })
    
    overlay.addEventListener('click', () => {
      const modals = document.querySelectorAll('.modal.active')
      modals.forEach(modal => {
        closeModal(modal)
      })
    })
    
    closeModalButtons.forEach(button => {
      button.addEventListener('click', () => {
        const modal = button.closest('.modal')
        closeModal(modal)
      })
    })
    
    function openModal(modal) {
      if (modal == null) return 
      modal.classList.add('active')
      overlay.classList.add('active')
    }
    
    function closeModal(modal) {
      if (modal == null) return 
      modal.classList.remove('active')
      overlay.classList.remove('active')

    }

}


iteamGeneration()
let datas = getDatas()
showImage(datas)
addFilmsInfos(datas)
modalManager()