// Modify the html core content
//


export async function showImage(getFunctionResult) {
// Modify film's covers
// Arg : An array of JSON datas generated by getDatas()
let filmsArray = await getFunctionResult;
for (let value in filmsArray) {
    const filmByCategory = filmsArray[value]
    if (value != 0) {
        for (let film in filmByCategory) {
            document.getElementById("img"+value+"-"+film).src = filmByCategory[film]['image_url'];
            
        }
    }
}
}


export async function addFilmsInfos(getFunctionResult) { 
    // Modify modals informations 
    // Arg : An array of JSON datas generated by getDatas()
    let filmsArray = await getFunctionResult;
    let index = 0
    for (let value in filmsArray) {
        const filmByCategory = filmsArray[value]
        if (value == 0) {
            let content = document.getElementById('modal'+index);
            content.firstElementChild.firstElementChild.innerHTML = filmsArray[value]['title'];
            let modalBody = document.getElementsByClassName('modal-body')[index];
            generateTable(index, filmsArray[value]);
            index +=1
            } 
        else {
            for (let film in filmByCategory) {
                let content = document.getElementById('modal'+index);
                content.firstElementChild.firstElementChild.innerHTML = filmByCategory[film]['title'];
                let modalBody = document.getElementsByClassName('modal-body')[index];
                generateTable(index, filmByCategory[film]);
                index += 1;
            }
        }
    }
} 


async function generateTable(tableIndex, datas) {
    // Create tables inside the html in order to represent films datas
    // Args : The table index : an int, data : film's informations ( JSON format )
    let data = await datas
    let table = document.querySelectorAll("table")[tableIndex]
    let unwantedElements = ["id","url","imdb_url","title","image_url"]
    for (let element in data) {
      if (!unwantedElements.includes(element)) {
        let tableKey = element;
        let tableValue = data[element];
        let row = table.insertRow();
  
        let cell1 = row.insertCell();
        let cell2 = row.insertCell();
  
        let text1 = document.createTextNode(tableKey);
        let text2 = document.createTextNode(tableValue);

        cell1.appendChild(text1);
        cell2.appendChild(text2);
      }
    }
  }
